apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/spring-financial-group/JX3_Azure_Vault_Production
      changes:
        - regex:
            pattern: >
              ghcr.io\/spring-financial-group\/peacock:(.*)
            files:
              - ".lighthouse/jenkins-x/peacock-release.yaml"
              - ".lighthouse/jenkins-x/peacock-verify.yaml"
