{{- if not .Values.serviceSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: peacock
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  git-token: {{ default "" .Values.gitToken | b64enc | quote }}
  github-secret: {{ default "" .Values.githubSecret | b64enc | quote }}
  slack-token: {{ default "" .Values.webhookSecret | b64enc | quote }}
  webhook-secret: {{ default "" .Values.webhookSecret | b64enc | quote }}
  webhook-token: {{ default "" .Values.webhookToken | b64enc | quote }}
  {{- end }}
