apiVersion: v1
kind: Secret
metadata:
  name: peacock-service
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  git-token: {{ default "" .Values.gitToken | b64enc | quote }}
  hmac-secret: {{ default "" .Values.hmacSecret | b64enc | quote }}
