// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "get the health of the dependencies of the service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Gets the health of the service",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/releases/{environment}": {
            "put": {
                "description": "Save a release",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "release"
                ],
                "summary": "Save a release",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Release Notes",
                        "name": "releaseNotes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ReleaseNote"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/releases/{environment}/after/{startTime}": {
            "get": {
                "description": "Get releases after a specific date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "release"
                ],
                "summary": "Get releases after a specific date",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start Time",
                        "name": "startTime",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/webhooks": {
            "post": {
                "description": "Endpoint for GitHub webhooks",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "webhook"
                ],
                "summary": "Endpoint for GitHub webhooks",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ReleaseNote": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "teams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Team"
                    }
                }
            }
        },
        "models.Team": {
            "type": "object",
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "apikey": {
                    "type": "string"
                },
                "contactType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.6.1-dev+7aa84e8",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Peacock API",
	Description:      "Service for notifying users of changes to your platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
