apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: peacock-verify
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - image: ghcr.io/jenkins-x/jx-boot:3.2.197
              name: token-export
              resources: {}
              script: |
                #!/usr/bin/env sh
                jx gitops variables --commit=false
                echo "export GITHUB_TOKEN=\"$(kubectl get secret peacock -n jx-staging -o jsonpath="{.data['gh-bot-token']}" | base64 -d)\"" >> .jx/variables.sh
                echo "export SLACK_TOKEN=\"$(kubectl get secret peacock -n jx-staging -o jsonpath="{.data['slack-token']}" | base64 -d)\"" >> .jx/variables.sh
              workingDir: /workspace/source
            - image: golang:1.18
              name: peacock-run
              resources: {}
              script: |
                #!/usr/bin/env bash
                source .jx/variables.sh
                make install
                peacock run --dry-run --comment-validation
              workingDir: /workspace/source
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
