apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
          env:
          - name: SwaggerServiceName
            value: Peacock
          - name: SpecPath
            value: ./docs/swagger.json
          - name: OutputLanguages
            value: csharp angular
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 600Mi
        - image: ghcr.io/jenkins-x/jx-boot:3.2.197
          name: override-docker-registry
          resources: {}
          script: |
            #!/usr/bin/env sh
            sed -i 's/jx3mqubebuild/mqubeoss/g' .jx/variables.sh
        - image: golang:1.22
          name: build-make-build
          resources: {}
          script: |
            #!/bin/sh
            make build
        - image: uses:spring-financial-group/DevOps/pipelines/sonar-scanner-pr.yaml@main
          name: ""
        - image: uses:spring-financial-group/DevOps/pipelines/build-scan-push-oss.yaml@main
          name: ""
          resources: {}
        - image: uses:spring-financial-group/DevOps/pipelines/preview-copy-secrets.yaml@main
          name: ""
          resources: {}
        - name: promote-jx-preview
          resources: {}
        - image: uses:spring-financial-group/jx3-openapi-generation/pipeline/generate-packages.yaml@master
          name: ""
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
