apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 600Mi
        - image: golang:1.18
          name: build-make-build
          resources: {}
          script: |
            #!/bin/sh
            make build
        - image: uses:spring-financial-group/DevOps/pipelines/sonar-scanner-pr.yaml@main
          name: ""
        - image: ghcr.io/jenkins-x/jx-boot:3.2.197
          name: override-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            echo "export GH_TOKEN=\"$(kubectl get secret peacock -n jx-staging -o jsonpath="{.data['git-token']}" | base64 -d)\"" >> .jx/variables.sh
        - image: gcr.io/kaniko-project/executor:v1.6.0-debug
          name: build-push-container
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            echo "{\"auths\":{\"ghcr.io\":{\"username\":\"peacock-bot\",\"password\":\"$GH_TOKEN\"}}}" > /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile --destination=ghcr.io/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --build-arg=VERSION=$VERSION
        - image: uses:spring-financial-group/DevOps/pipelines/preview-copy-secrets.yaml@main
          name: ""
          resources: {}
        - image: ghcr.io/jenkins-x-plugins/jx-preview:0.0.231
          name: promote-jx-preview
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            export DOCKER_REGISTRY=ghcr.io
            jx preview create
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
