apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-cli/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 600Mi
        - image: golang:1.18
          name: build-make-linux
          resources: {}
          script: |
            #!/bin/sh
            make linux
        - image: uses:spring-financial-group/DevOps/pipelines/sonar-scanner-pr.yaml@main
          name: ""
        - image: ghcr.io/jenkins-x/jx-boot:3.2.197
          name: ghcr-token-export
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
            kubectl get secret peacock-ghcr -n jx-staging -o jsonpath="{.data['token']}" | base64 -d > /workspace/source/ghcr-token.gt
        - image: gcr.io/kaniko-project/executor:v1.6.0-debug
          name: build-push-container
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            echo "{\"auths\":{\"ghcr.io\":{\"username\":\"mqube-bot\",\"password\":\"$(cat /workspace/source/ghcr-token.gt)\"}}}" > /kaniko/.docker/config.json
            rm /workspace/source/ghcr-token.gt
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile --destination=ghcr.io/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --build-arg=VERSION=$VERSION
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
