apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
          volumeMounts:
            - mountPath: /oss-docker-config
              name: oss-docker-config
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources:
            # override requests for the pod here
            requests:
              cpu: 400m
              memory: 600Mi
        - image: ghcr.io/jenkins-x/jx-boot:3.2.197
          name: override-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            sed -i 's/jx3mqubebuild/mqubeoss/g' .jx/variables.sh
            sed -i -E "s/JX_CHART_REPOSITORY=(.*?)/JX_CHART_REPOSITORY='mqubeoss.azurecr.io'/g" .jx/variables.sh
            cat .jx/variables.sh
        - image: golang:1.19
          name: build-make-build
          resources: {}
          script: |
            #!/bin/sh
            make build
        - image: uses:spring-financial-group/DevOps/pipelines/sonar-scanner-pr.yaml@main
          name: ""
        - image: gcr.io/kaniko-project/executor:v1.9.1-debug
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /oss-docker-config/config.json /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - image: ghcr.io/jenkins-x/jx-boot:3.10.45
          name: promote-helm-release
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            
            USER=$(kubectl get secret tekton-oss-container-registry-auth -n jx -o jsonpath="{.data['adminuser']}" | base64 -d)
            PASS=$(kubectl get secret tekton-oss-container-registry-auth -n jx -o jsonpath="{.data['adminpass']}" | base64 -d)
            
            jx gitops helm release --oci --version $VERSION -u mqubeoss.azurecr.io/spring-financial-group --repo-username $USER --repo-password $PASS
        - image: uses:spring-financial-group/DevOps/pipelines/preview-copy-secrets.yaml@main
          name: ""
          resources: {}
        - image: ghcr.io/jenkins-x-plugins/jx-preview:0.0.231
          name: promote-jx-preview
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx preview create
        volumes:
          - name: oss-docker-config
            secret:
              secretName: tekton-oss-container-registry-auth
              items:
                - key: .dockerconfigjson
                  path: config.json
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
