apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: gl
    context: "golint"
    always_run: true
    optional: false
    source: "golint.yaml"
  - name: pr
    context: "pr"
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  - name: commit-semantics-check
    context: "commit-semantics-check"
    always_run: true
    optional: false
    source: "semanticcheck.yaml"
  - name: tests
    context: "run-tests"
    always_run: true
    optional: false
    source: "tests.yaml"
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
