// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "github.com/spring-financial-group/peacock/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ReleaseNotesUseCase is an autogenerated mock type for the ReleaseNotesUseCase type
type ReleaseNotesUseCase struct {
	mock.Mock
}

// AppendReleaseNotesToExistingMarkdown provides a mock function with given fields: existingMarkdown, releaseNotesToAppend
func (_m *ReleaseNotesUseCase) AppendReleaseNotesToExistingMarkdown(existingMarkdown string, releaseNotesToAppend []models.ReleaseNote) (string, error) {
	ret := _m.Called(existingMarkdown, releaseNotesToAppend)

	if len(ret) == 0 {
		panic("no return value specified for AppendReleaseNotesToExistingMarkdown")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []models.ReleaseNote) (string, error)); ok {
		return rf(existingMarkdown, releaseNotesToAppend)
	}
	if rf, ok := ret.Get(0).(func(string, []models.ReleaseNote) string); ok {
		r0 = rf(existingMarkdown, releaseNotesToAppend)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, []models.ReleaseNote) error); ok {
		r1 = rf(existingMarkdown, releaseNotesToAppend)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateBreakdown provides a mock function with given fields: notes, hash, totalTeams
func (_m *ReleaseNotesUseCase) GenerateBreakdown(notes []models.ReleaseNote, hash string, totalTeams int) (string, error) {
	ret := _m.Called(notes, hash, totalTeams)

	if len(ret) == 0 {
		panic("no return value specified for GenerateBreakdown")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]models.ReleaseNote, string, int) (string, error)); ok {
		return rf(notes, hash, totalTeams)
	}
	if rf, ok := ret.Get(0).(func([]models.ReleaseNote, string, int) string); ok {
		r0 = rf(notes, hash, totalTeams)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]models.ReleaseNote, string, int) error); ok {
		r1 = rf(notes, hash, totalTeams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateHash provides a mock function with given fields: messages
func (_m *ReleaseNotesUseCase) GenerateHash(messages []models.ReleaseNote) (string, error) {
	ret := _m.Called(messages)

	if len(ret) == 0 {
		panic("no return value specified for GenerateHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]models.ReleaseNote) (string, error)); ok {
		return rf(messages)
	}
	if rf, ok := ret.Get(0).(func([]models.ReleaseNote) string); ok {
		r0 = rf(messages)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]models.ReleaseNote) error); ok {
		r1 = rf(messages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMarkdownFromReleaseNotes provides a mock function with given fields: notes
func (_m *ReleaseNotesUseCase) GetMarkdownFromReleaseNotes(notes []models.ReleaseNote) string {
	ret := _m.Called(notes)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkdownFromReleaseNotes")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func([]models.ReleaseNote) string); ok {
		r0 = rf(notes)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetReleaseNotesFromMarkdownAndTeamsInFeathers provides a mock function with given fields: markdown, teamsInFeathers
func (_m *ReleaseNotesUseCase) GetReleaseNotesFromMarkdownAndTeamsInFeathers(markdown string, teamsInFeathers models.Teams) ([]models.ReleaseNote, error) {
	ret := _m.Called(markdown, teamsInFeathers)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseNotesFromMarkdownAndTeamsInFeathers")
	}

	var r0 []models.ReleaseNote
	var r1 error
	if rf, ok := ret.Get(0).(func(string, models.Teams) ([]models.ReleaseNote, error)); ok {
		return rf(markdown, teamsInFeathers)
	}
	if rf, ok := ret.Get(0).(func(string, models.Teams) []models.ReleaseNote); ok {
		r0 = rf(markdown, teamsInFeathers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ReleaseNote)
		}
	}

	if rf, ok := ret.Get(1).(func(string, models.Teams) error); ok {
		r1 = rf(markdown, teamsInFeathers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseReleaseNoteFromMarkdown provides a mock function with given fields: markdown, sanitise
func (_m *ReleaseNotesUseCase) ParseReleaseNoteFromMarkdown(markdown string, sanitise bool) (string, []models.ReleaseNote, error) {
	ret := _m.Called(markdown, sanitise)

	if len(ret) == 0 {
		panic("no return value specified for ParseReleaseNoteFromMarkdown")
	}

	var r0 string
	var r1 []models.ReleaseNote
	var r2 error
	if rf, ok := ret.Get(0).(func(string, bool) (string, []models.ReleaseNote, error)); ok {
		return rf(markdown, sanitise)
	}
	if rf, ok := ret.Get(0).(func(string, bool) string); ok {
		r0 = rf(markdown, sanitise)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, bool) []models.ReleaseNote); ok {
		r1 = rf(markdown, sanitise)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]models.ReleaseNote)
		}
	}

	if rf, ok := ret.Get(2).(func(string, bool) error); ok {
		r2 = rf(markdown, sanitise)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PopulateTeamsInReleaseNotes provides a mock function with given fields: releaseNotes, teamsInFeathers
func (_m *ReleaseNotesUseCase) PopulateTeamsInReleaseNotes(releaseNotes []models.ReleaseNote, teamsInFeathers models.Teams) error {
	ret := _m.Called(releaseNotes, teamsInFeathers)

	if len(ret) == 0 {
		panic("no return value specified for PopulateTeamsInReleaseNotes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]models.ReleaseNote, models.Teams) error); ok {
		r0 = rf(releaseNotes, teamsInFeathers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendReleaseNotes provides a mock function with given fields: subject, notes
func (_m *ReleaseNotesUseCase) SendReleaseNotes(subject string, notes []models.ReleaseNote) error {
	ret := _m.Called(subject, notes)

	if len(ret) == 0 {
		panic("no return value specified for SendReleaseNotes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []models.ReleaseNote) error); ok {
		r0 = rf(subject, notes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReleaseNotesUseCase creates a new instance of ReleaseNotesUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReleaseNotesUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReleaseNotesUseCase {
	mock := &ReleaseNotesUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
