// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/spring-financial-group/peacock/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// SCMClientFactory is an autogenerated mock type for the SCMClientFactory type
type SCMClientFactory struct {
	mock.Mock
}

// GetClient provides a mock function with given fields: owner, repo, user, prNumber
func (_m *SCMClientFactory) GetClient(owner string, repo string, user string, prNumber int) domain.SCM {
	ret := _m.Called(owner, repo, user, prNumber)

	var r0 domain.SCM
	if rf, ok := ret.Get(0).(func(string, string, string, int) domain.SCM); ok {
		r0 = rf(owner, repo, user, prNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.SCM)
		}
	}

	return r0
}

// RemoveClient provides a mock function with given fields: key
func (_m *SCMClientFactory) RemoveClient(key string) {
	_m.Called(key)
}

type mockConstructorTestingTNewSCMClientFactory interface {
	mock.TestingT
	Cleanup(func())
}

// NewSCMClientFactory creates a new instance of SCMClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSCMClientFactory(t mockConstructorTestingTNewSCMClientFactory) *SCMClientFactory {
	mock := &SCMClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
