// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/spring-financial-group/peacock/pkg/models"
)

// UserReleaseTrackingRepository is an autogenerated mock type for the UserReleaseTrackingRepository type
type UserReleaseTrackingRepository struct {
	mock.Mock
}

// GetUserTracking provides a mock function with given fields: ctx, userID, environment
func (_m *UserReleaseTrackingRepository) GetUserTracking(ctx context.Context, userID string, environment string) (*models.UserReleaseTracking, error) {
	ret := _m.Called(ctx, userID, environment)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTracking")
	}

	var r0 *models.UserReleaseTracking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.UserReleaseTracking, error)); ok {
		return rf(ctx, userID, environment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.UserReleaseTracking); ok {
		r0 = rf(ctx, userID, environment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserReleaseTracking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, environment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkReleasesViewed provides a mock function with given fields: ctx, userID, environment, releaseIDs
func (_m *UserReleaseTrackingRepository) MarkReleasesViewed(ctx context.Context, userID string, environment string, releaseIDs []string) error {
	ret := _m.Called(ctx, userID, environment, releaseIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkReleasesViewed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = rf(ctx, userID, environment, releaseIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertUserTracking provides a mock function with given fields: ctx, tracking
func (_m *UserReleaseTrackingRepository) UpsertUserTracking(ctx context.Context, tracking *models.UserReleaseTracking) error {
	ret := _m.Called(ctx, tracking)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserTracking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserReleaseTracking) error); ok {
		r0 = rf(ctx, tracking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserReleaseTrackingRepository creates a new instance of UserReleaseTrackingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserReleaseTrackingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserReleaseTrackingRepository {
	mock := &UserReleaseTrackingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
